eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.16/mysql
    username: root
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service
server:
  port: 9001      
